# Generated by Django 2.2.24 on 2022-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='num_of_ingredients',
            field=models.IntegerField(default=0),
        ),
    ]
